/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utbk_mahasiswa;

/**
 *
 * @author asus
 */
public class frame_utbk extends javax.swing.JFrame {

    /**
     * Creates new form frame_utbk
     */
    public frame_utbk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nisn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdb_laki2 = new javax.swing.JRadioButton();
        rdb_perempuan = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtr_asal = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        rdb_ipa = new javax.swing.JRadioButton();
        rdb_ips = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        chk_login = new javax.swing.JCheckBox();
        chk_biodata = new javax.swing.JCheckBox();
        chk_prodi = new javax.swing.JCheckBox();
        chk_portofolio = new javax.swing.JCheckBox();
        chk_kartu = new javax.swing.JCheckBox();
        txt_label = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(102, 255, 102));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATA UTBK 2021");

        jLabel2.setText("NAMA");

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        jLabel3.setText("NISN");

        txt_nisn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nisnActionPerformed(evt);
            }
        });

        jLabel4.setText("JENIS KELAMIN");

        btn_group.add(rdb_laki2);
        rdb_laki2.setText("LAKI-LAKI");
        rdb_laki2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_laki2ActionPerformed(evt);
            }
        });

        btn_group.add(rdb_perempuan);
        rdb_perempuan.setText("PEREMPUAN");

        jLabel7.setText("ASAL SEKOLAH");

        txtr_asal.setColumns(20);
        txtr_asal.setRows(5);
        txtr_asal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtr_asalCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(txtr_asal);

        jLabel8.setText("KETENTUAN PILIHAN PTN");

        buttonGroup1.add(rdb_ipa);
        rdb_ipa.setText("IPA");

        buttonGroup1.add(rdb_ips);
        rdb_ips.setText("IPS");

        jLabel9.setText("SYARAT PENDAFTARAN YANG SUDAH TERPENUHI");

        chk_login.setText("LOGIN AKUN");

        chk_biodata.setText("MELENGKAPI BIODATA");

        chk_prodi.setText("MEMILIH PROGRAM STUDI");

        chk_portofolio.setText("MENGUNGGAH PORTOFOLIO");

        chk_kartu.setText("UNDUH KARTU PESERTA");

        txt_label.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        txt_label.setForeground(new java.awt.Color(51, 51, 0));
        txt_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_label.setText("Data");
        txt_label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(559, 559, 559)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(113, 113, 113)))
                                .addGap(578, 578, 578))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(124, 124, 124)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdb_perempuan)
                                            .addComponent(rdb_laki2)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdb_ips)
                                            .addComponent(rdb_ipa)
                                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_nisn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btn_save))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(chk_login)
                            .addComponent(chk_biodata)
                            .addComponent(chk_prodi)
                            .addComponent(chk_portofolio)
                            .addComponent(chk_kartu))
                        .addGap(544, 544, 544))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_label, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(123, 123, 123)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chk_login)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_nisn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rdb_laki2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdb_perempuan)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(rdb_ipa)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(chk_biodata)
                        .addGap(18, 18, 18)
                        .addComponent(chk_prodi)
                        .addGap(18, 18, 18)
                        .addComponent(chk_portofolio)
                        .addGap(18, 18, 18)
                        .addComponent(chk_kartu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdb_ips)
                .addGap(27, 27, 27)
                .addComponent(btn_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_label, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_nisnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nisnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nisnActionPerformed

    private void rdb_laki2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_laki2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_laki2ActionPerformed

    private void txtr_asalCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtr_asalCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtr_asalCaretUpdate

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        String nama, nisn, jenkel, asal, ptn, syarat = null;
        
        nama = txt_name.getText();
        nisn = txt_nisn.getText();
        asal = txtr_asal.getText();
        
        
        
        if (rdb_laki2.isSelected()){
            jenkel = rdb_laki2.getText();
        }else{
         jenkel = rdb_perempuan.getText();
    }
        
        if(rdb_ipa.isSelected()){
            ptn = rdb_ipa.getText();
        }else{
            ptn = rdb_ips.getText();
        }
        
        if (chk_login.isSelected())
        {
            syarat = chk_login.getText();
            
            if (chk_biodata.isSelected())
            {
            syarat = chk_login.getText()+ "," +chk_biodata.getText();
               
            if (chk_prodi.isSelected())
            {
            syarat = chk_login.getText()+ ","+chk_biodata.getText() + ","+chk_prodi.getText();
                 
               if (chk_portofolio.isSelected())
               {
               syarat = chk_login.getText()+ ","+chk_biodata.getText() + "," +chk_prodi.getText()+ ","+chk_portofolio.getText(); 
                        
                  if (chk_kartu.isSelected())
                  {
                  syarat = chk_login.getText()+ ","+chk_biodata.getText() + "," +chk_prodi.getText()+ ","+chk_portofolio.getText() + ","+chk_kartu.getText();
                  }
                }
               }
            }
      
       }
        
      txt_label.setText("<html>" +"NAMA : "+nama +"<br>"
                          +"NISN : "+nisn +"<br>"
                          +"JENIS KELAMIN : "+jenkel +"<br>"
                          +"PTN : "+ptn +"<br>"
                          +"ASAL SEKOLAH : " +asal +"<br>"
                          +"SYARAT : "+syarat +"</html>");
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_utbk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_utbk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_utbk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_utbk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_utbk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn_group;
    private javax.swing.JButton btn_save;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chk_biodata;
    private javax.swing.JCheckBox chk_kartu;
    private javax.swing.JCheckBox chk_login;
    private javax.swing.JCheckBox chk_portofolio;
    private javax.swing.JCheckBox chk_prodi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdb_ipa;
    private javax.swing.JRadioButton rdb_ips;
    private javax.swing.JRadioButton rdb_laki2;
    private javax.swing.JRadioButton rdb_perempuan;
    private javax.swing.JLabel txt_label;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nisn;
    private javax.swing.JTextArea txtr_asal;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
