package com.kruwell.program;

import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class covid extends javax.swing.JFrame {
    
    private void kosongkan_form(){
        txtno_kasus.setEditable(true);
        txtno_kasus.setText(null);
        txtnama.setText(null);
        cbjeniskelamin.setSelectedItem(this);
        txtalamat.setText(null);
        txtumur.setText(null);
        txtprovinsi.setText(null);
    }
     
    private void tampilkan_data(){
       DefaultTableModel model = new DefaultTableModel();
       model.addColumn("No.");
       model.addColumn("No Kasus");
       model.addColumn("Nama");
       model.addColumn("Jenis Kelamin");
       model.addColumn("Umur");
       model.addColumn("Alamat");
       model.addColumn("Provinsi");
       
       try {
           int no = 1;
           String sql = "SELECT * FROM covid19";
           java.sql.Connection conn = (Connection)konfig.configDB();
           java.sql.Statement stm = conn.createStatement();
           java.sql.ResultSet res = stm.executeQuery(sql);
           
           
          while (res.next()){
              model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6) });
              
          }
          tabelcovid.setModel(model);
          
       }catch(SQLException e){
           System.out.println("Error  : " + e.getMessage());
       }
       
    }
    /**
     * Creates new form covid
     */
    public covid() {
        initComponents();
        tampilkan_data();
        kosongkan_form();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodypanel = new javax.swing.JPanel();
        menupanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        aboutview = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnhome1 = new javax.swing.JButton();
        btndata = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tbkeluar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        homepanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbjeniskelamin = new javax.swing.JComboBox<>();
        tbsimpan = new javax.swing.JButton();
        tbbatal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtno_kasus = new javax.swing.JTextField();
        txtumur = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tbedit = new javax.swing.JButton();
        txtalamat = new javax.swing.JTextField();
        labelprovinsi = new javax.swing.JLabel();
        txtprovinsi = new javax.swing.JTextField();
        labelalamat = new javax.swing.JLabel();
        tbtambah = new javax.swing.JButton();
        datapanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tbhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelcovid = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Data Kasus");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bodypanel.setBackground(new java.awt.Color(255, 51, 51));
        bodypanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menupanel.setBackground(new java.awt.Color(255, 51, 51));
        menupanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        menupanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menupanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        aboutview.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        aboutview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kruwell/program/icons8-about-32.png"))); // NOI18N
        aboutview.setText("ABOUT US");
        aboutview.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aboutview.setIconTextGap(10);
        aboutview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutviewActionPerformed(evt);
            }
        });
        menupanel.add(aboutview, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 190, 80));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kruwell/program/icons8-virus-64.png"))); // NOI18N
        jLabel9.setText("DATA");
        menupanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 90));

        btnhome1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnhome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kruwell/program/icons8-home-32.png"))); // NOI18N
        btnhome1.setText("HOME");
        btnhome1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnhome1.setIconTextGap(10);
        btnhome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhome1ActionPerformed(evt);
            }
        });
        menupanel.add(btnhome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 190, 80));

        btndata.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btndata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kruwell/program/icons8-table-32.png"))); // NOI18N
        btndata.setText("DATA");
        btndata.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndata.setIconTextGap(10);
        btndata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndataActionPerformed(evt);
            }
        });
        menupanel.add(btndata, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 190, 80));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kruwell/program/icons8-virus-64.png"))); // NOI18N
        jLabel10.setText("KASUS");
        menupanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, 80));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kruwell/program/icons8-virus-64.png"))); // NOI18N
        jLabel11.setText("COVID-19");
        menupanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 70));

        tbkeluar.setBackground(new java.awt.Color(255, 255, 255));
        tbkeluar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tbkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kruwell/program/icons8-export-32.png"))); // NOI18N
        tbkeluar.setText("LOGOUT");
        tbkeluar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbkeluar.setIconTextGap(10);
        tbkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbkeluarActionPerformed(evt);
            }
        });
        menupanel.add(tbkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 190, 80));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("HOME");
        menupanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 150, 40));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("#STAY AT ");
        menupanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 320, 40));

        bodypanel.add(menupanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 760));

        mainpanel.setLayout(new java.awt.CardLayout());

        homepanel.setBackground(new java.awt.Color(255, 51, 51));
        homepanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        homepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JENIS KELAMIN");
        homepanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 210, 40));

        cbjeniskelamin.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cbjeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRIA", "WANITA" }));
        cbjeniskelamin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbjeniskelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjeniskelaminActionPerformed(evt);
            }
        });
        homepanel.add(cbjeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 280, 40));

        tbsimpan.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kruwell/program/icons8-save-40.png"))); // NOI18N
        tbsimpan.setText("Simpan");
        tbsimpan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbsimpanActionPerformed(evt);
            }
        });
        homepanel.add(tbsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 620, 160, 60));

        tbbatal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kruwell/program/icons8-cancel-40.png"))); // NOI18N
        tbbatal.setText("Batal");
        tbbatal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbbatalActionPerformed(evt);
            }
        });
        homepanel.add(tbbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 160, 60));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("UMUR");
        homepanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 100, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAMA");
        homepanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 110, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMOR KASUS");
        homepanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 180, 40));

        txtnama.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        homepanel.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 370, 30));

        txtno_kasus.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtno_kasus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtno_kasusActionPerformed(evt);
            }
        });
        homepanel.add(txtno_kasus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 370, 30));

        txtumur.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        homepanel.add(txtumur, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 370, 30));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA PASIEN");
        homepanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 420, 60));

        tbedit.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kruwell/program/icons8-edit-40.png"))); // NOI18N
        tbedit.setText("Edit Data");
        tbedit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbeditActionPerformed(evt);
            }
        });
        homepanel.add(tbedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 160, 60));

        txtalamat.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });
        homepanel.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 370, 40));

        labelprovinsi.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelprovinsi.setForeground(new java.awt.Color(255, 255, 255));
        labelprovinsi.setText("PROVINSI");
        homepanel.add(labelprovinsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 140, 40));

        txtprovinsi.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtprovinsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprovinsiActionPerformed(evt);
            }
        });
        homepanel.add(txtprovinsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 370, 30));

        labelalamat.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelalamat.setForeground(new java.awt.Color(255, 255, 255));
        labelalamat.setText("ALAMAT");
        homepanel.add(labelalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 130, 40));

        tbtambah.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbtambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kruwell/program/icons8-input-40.png"))); // NOI18N
        tbtambah.setText("Tambah Data");
        tbtambah.setAutoscrolls(true);
        tbtambah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtambahActionPerformed(evt);
            }
        });
        homepanel.add(tbtambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 180, 60));

        mainpanel.add(homepanel, "card3");

        datapanel.setBackground(new java.awt.Color(0, 204, 204));
        datapanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        datapanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel16.setText("MENU DATA");
        datapanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 240, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kruwell/program/coronaa.jpg"))); // NOI18N
        datapanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        tbhapus.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kruwell/program/icons8-delete-view-40.png"))); // NOI18N
        tbhapus.setText("Hapus Data");
        tbhapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbhapusActionPerformed(evt);
            }
        });
        datapanel.add(tbhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 190, 50));

        tabelcovid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelcovid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelcovidMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelcovid);

        datapanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 740, 240));

        mainpanel.add(datapanel, "card17");

        bodypanel.add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 810, 760));

        getContentPane().add(bodypanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbjeniskelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjeniskelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbjeniskelaminActionPerformed

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void tbkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbkeluarActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin ingin keluar?", "PERINGATAN", dialogBtn);
                
           if (dialogResult ==0){
               System.exit(0);
           } 
           else {}
    }//GEN-LAST:event_tbkeluarActionPerformed

    private void tbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtambahActionPerformed
        // TODO add your handling code here:
        
        kosongkan_form();
     
    }//GEN-LAST:event_tbtambahActionPerformed

    private void tbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbsimpanActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO covid19 VALUES('"+txtno_kasus.getText()+"','"+txtnama.getText()+"','"+cbjeniskelamin.getSelectedItem()+"',"
                    + "'"+txtumur.getText()+"','"+txtalamat.getText()+"','"+txtprovinsi.getText()+"')";
            java.sql.Connection conn = (Connection)konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil...");
            tampilkan_data();
            kosongkan_form();
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tbsimpanActionPerformed

    private void tbeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbeditActionPerformed
        // TODO add your handling code here:
        try {
         String sql = "UPDATE covid19 SET no_kasus = '"+txtno_kasus.getText()+"',nama = '"+txtnama.getText()+"',jenis_kelamin = '"+cbjeniskelamin.getSelectedItem()+"',"
                 + "umur = '"+txtumur.getText()+"', alamat = '"+txtalamat.getText()+"',provinsi ='"+txtprovinsi.getText()+"' WHERE no_kasus = '"+txtno_kasus.getText()+"'";
         java.sql.Connection conn = (Connection)konfig.configDB();
         java.sql.PreparedStatement pstm =  conn.prepareStatement(sql);
         pstm.execute();
         JOptionPane.showMessageDialog(null, "Edit Data Berhasil...");
         
         
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_tbeditActionPerformed

    private void tabelcovidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelcovidMouseClicked
        // TODO add your handling code here:
        int baris = tabelcovid.rowAtPoint(evt.getPoint());
        String no_kasus = tabelcovid.getValueAt(baris, 1).toString();
        txtno_kasus.setText(no_kasus);
        
        String nama = tabelcovid.getValueAt(baris, 2).toString();
        txtnama.setText(nama);
        
        String jeniskelamin = tabelcovid.getValueAt(baris, 3).toString();
        cbjeniskelamin.setSelectedItem(jeniskelamin);
        
         String umur = tabelcovid.getValueAt(baris, 4).toString();
        txtumur.setText(umur);
        
        String alamat = tabelcovid.getValueAt(baris, 5).toString();
        txtalamat.setText(alamat);
        
        String provinsi = tabelcovid.getValueAt(baris, 6).toString();
        txtprovinsi.setText(provinsi);
    }//GEN-LAST:event_tabelcovidMouseClicked

    private void tbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbhapusActionPerformed
        // TODO add your handling code here:
        try {
          String sql = "DELETE FROM covid19 WHERE no_kasus='"+txtno_kasus.getText()+"'";
         java.sql.Connection conn = (Connection)konfig.configDB();
         java.sql.PreparedStatement pstm =  conn.prepareStatement(sql);
         pstm.execute();
         JOptionPane.showMessageDialog(null, "Hapus Data Berhasil...");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_tbhapusActionPerformed

    private void tbbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbbatalActionPerformed
        // TODO add your handling code here:
        kosongkan_form();
    }//GEN-LAST:event_tbbatalActionPerformed

    private void txtno_kasusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtno_kasusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtno_kasusActionPerformed

    private void aboutviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutviewActionPerformed
        // TODO add your handling code here:
        aboutview n = new aboutview();
        n.setVisible(true);
    }//GEN-LAST:event_aboutviewActionPerformed

    private void btnhome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhome1ActionPerformed
        // TODO add your handling code here:
        
        //remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        //add panel
        mainpanel.add(homepanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_btnhome1ActionPerformed

    private void btndataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndataActionPerformed
        // TODO add your handling code here:
           //remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        //add panel
        mainpanel.add(datapanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_btndataActionPerformed

    private void txtprovinsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprovinsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprovinsiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(covid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(covid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(covid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(covid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new covid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutview;
    private javax.swing.JPanel bodypanel;
    private javax.swing.JButton btndata;
    private javax.swing.JButton btnhome1;
    private javax.swing.JComboBox<String> cbjeniskelamin;
    private javax.swing.JPanel datapanel;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelalamat;
    private javax.swing.JLabel labelprovinsi;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel menupanel;
    private javax.swing.JTable tabelcovid;
    private javax.swing.JButton tbbatal;
    private javax.swing.JButton tbedit;
    private javax.swing.JButton tbhapus;
    private javax.swing.JButton tbkeluar;
    private javax.swing.JButton tbsimpan;
    private javax.swing.JButton tbtambah;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtno_kasus;
    private javax.swing.JTextField txtprovinsi;
    private javax.swing.JTextField txtumur;
    // End of variables declaration//GEN-END:variables
}
